### ISSUE TITLE
OSS-cn-shanghai determined as invalid region

### ISSUE THREAD

**Issue by streamliner18** [yyang/cfs-aliyun#4]
如题。

Aliyun has added several regions since the creation of cfs:aliyun. Is the constraint in OSS region only implemented as a check? If that is, I will make a short PR.

**Comment by yyang** [comment]
Yes that is only used as a check. Please make the PR. Thanks.

Sent from my iPhone

On Jul 7, 2016, at 7:49 PM, StreamLiner <notifications@github.com<mailto:notifications@github.com>> wrote:

???

Aliyun has added several regions since the creation of cfs:aliyun. Is the constraint in OSS region only implemented as a check? If that is, I will make a short PR.

##

**Comment by yyang** [comment]
Updated via commit: 7a739c7e06610486537d61b44a252f975dac0271

Finally able to do meteor publish.
